version: "3.8"

services:

  postgres:
    image: postgres:18
    container_name: booking_postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: bus_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bus_booking"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./bus-booking-api
    container_name: booking_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bus_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./bus-booking-client
    container_name: booking_frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:8080
      API_BASE_URL: http://backend:8080/api
    depends_on:
      - backend

volumes:
  postgres18_data: